# Generated by Django 4.2.6 on 2023-10-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, verbose_name='reg_date'),
        ),
    ]
