# Generated by Django 4.2.6 on 2023-10-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reg_date',
            field=models.DateTimeField(verbose_name='reg_date'),
        ),
    ]
